# Generated by Django 5.0.2 on 2024-03-14 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_alter_breakdown_answer_alter_breakdown_correct'),
    ]

    operations = [
        migrations.AddField(
            model_name='exammodule',
            name='score',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
